### ISSUE TITLE
Why the run_exp.sh is useless?

### ISSUE THREAD

**Issue by zxr111** [nusnlp/probe-bert-transitivity#1]
When I run it occurs run_exp.sh: 15: Syntax error: "(" unexpected

**Comment by ruixilin** [comment]
> 

Hello, your problem seemed to be related to your system's bash environment, not with the script. Did you run the first line of run_exp.sh #!/usr/bin/env bash? Or you could try #!/bin/bash, or search for the correct way to run bash in your system.
