### ISSUE TITLE
Why it say with can't find file vecs_train.txt

### ISSUE THREAD

**Issue by zxr111** [nusnlp/probe-bert-transitivity#2]
with open(input_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '*/vecs_train.txt'

**Comment by zxr111** [comment]
and where can I find it

**Comment by ruixilin** [comment]
Hello, you can follow the example in README to put the data folder under the project directory which contains the source code and dependencies, and see the Instructions at probe-bert-transitivity/data/fullprobe to download the datasets at [ACL_2022_probing_datasets](https://drive.google.com/file/d/1JN0XcwVZnMgDKG09IRFZf81t8tDgeeVl/view?usp=sharing).

**Comment by zxr111** [comment]
But I can't find the vecs_train.txt and vecs_test.txt




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nusnlp/probe-bert-transitivity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月4日(星期天) 晚上9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nusnlp/probe-bert-transitivity] Why it say with can't find file vecs_train.txt (Issue #2)





 
Hello, you can follow the example in README to put the data folder under the project directory which contains the source code and dependencies, and see the Instructions at probe-bert-transitivity/data/fullprobe to download the datasets at ACL_2022_probing_datasets.

**Comment by ruixilin** [comment]
> But I can't find the vecs_train.txt and vecs_test.txt
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "nusnlp/probe-bert-transitivity" ***@***.***&gt;; 发送时间:&nbsp;2022年9月4日(星期天) 晚上9:57 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [nusnlp/probe-bert-transitivity] Why it say with can't find file vecs_train.txt (Issue #2) Hello, you can follow the example in README to put the data folder under the project directory which contains the source code and dependencies, and see the Instructions at probe-bert-transitivity/data/fullprobe to download the datasets at ACL_2022_probing_datasets. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Hi, the vecs_train.txt and vecs_test.txt files are inside the corresponding folders of [ACL_2022_probing_datasets](https://drive.google.com/file/d/1JN0XcwVZnMgDKG09IRFZf81t8tDgeeVl/view?usp=sharing).
